/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksGutenbergIdChaptersIdxRouteImport } from './routes/books.$gutenbergId.chapters.$idx'
import { Route as ProjectsProjectIdChaptersIdxRouteImport } from './routes/projects.$projectId.chapters.$idx'
import { Route as ProjectsProjectIdChaptersIdxEditRouteImport } from './routes/projects.$projectId.chapters.$idx_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksGutenbergIdChaptersIdxRoute =
  BooksGutenbergIdChaptersIdxRouteImport.update({
    id: '/books/$gutenbergId/chapters/$idx',
    path: '/books/$gutenbergId/chapters/$idx',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdChaptersIdxRoute =
  ProjectsProjectIdChaptersIdxRouteImport.update({
    id: '/projects/$projectId/chapters/$idx',
    path: '/projects/$projectId/chapters/$idx',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdChaptersIdxEditRoute =
  ProjectsProjectIdChaptersIdxEditRouteImport.update({
    id: '/projects/$projectId/chapters/$idx_/edit',
    path: '/projects/$projectId/chapters/$idx/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/books/$gutenbergId/chapters/$idx': typeof BooksGutenbergIdChaptersIdxRoute
  '/projects/$projectId/chapters/$idx': typeof ProjectsProjectIdChaptersIdxRoute
  '/projects/$projectId/chapters/$idx/edit': typeof ProjectsProjectIdChaptersIdxEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/books': typeof BooksIndexRoute
  '/books/$gutenbergId/chapters/$idx': typeof BooksGutenbergIdChaptersIdxRoute
  '/projects/$projectId/chapters/$idx': typeof ProjectsProjectIdChaptersIdxRoute
  '/projects/$projectId/chapters/$idx/edit': typeof ProjectsProjectIdChaptersIdxEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/books/$gutenbergId/chapters/$idx': typeof BooksGutenbergIdChaptersIdxRoute
  '/projects/$projectId/chapters/$idx': typeof ProjectsProjectIdChaptersIdxRoute
  '/projects/$projectId/chapters/$idx_/edit': typeof ProjectsProjectIdChaptersIdxEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/projects'
    | '/admin/users'
    | '/admin/'
    | '/books/'
    | '/books/$gutenbergId/chapters/$idx'
    | '/projects/$projectId/chapters/$idx'
    | '/projects/$projectId/chapters/$idx/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/projects'
    | '/admin/users'
    | '/admin'
    | '/books'
    | '/books/$gutenbergId/chapters/$idx'
    | '/projects/$projectId/chapters/$idx'
    | '/projects/$projectId/chapters/$idx/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/projects'
    | '/admin/users'
    | '/admin/'
    | '/books/'
    | '/books/$gutenbergId/chapters/$idx'
    | '/projects/$projectId/chapters/$idx'
    | '/projects/$projectId/chapters/$idx_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BooksIndexRoute: typeof BooksIndexRoute
  BooksGutenbergIdChaptersIdxRoute: typeof BooksGutenbergIdChaptersIdxRoute
  ProjectsProjectIdChaptersIdxRoute: typeof ProjectsProjectIdChaptersIdxRoute
  ProjectsProjectIdChaptersIdxEditRoute: typeof ProjectsProjectIdChaptersIdxEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$gutenbergId/chapters/$idx': {
      id: '/books/$gutenbergId/chapters/$idx'
      path: '/books/$gutenbergId/chapters/$idx'
      fullPath: '/books/$gutenbergId/chapters/$idx'
      preLoaderRoute: typeof BooksGutenbergIdChaptersIdxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/chapters/$idx': {
      id: '/projects/$projectId/chapters/$idx'
      path: '/projects/$projectId/chapters/$idx'
      fullPath: '/projects/$projectId/chapters/$idx'
      preLoaderRoute: typeof ProjectsProjectIdChaptersIdxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/chapters/$idx_/edit': {
      id: '/projects/$projectId/chapters/$idx_/edit'
      path: '/projects/$projectId/chapters/$idx/edit'
      fullPath: '/projects/$projectId/chapters/$idx/edit'
      preLoaderRoute: typeof ProjectsProjectIdChaptersIdxEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProjectsRoute: AdminProjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BooksIndexRoute: BooksIndexRoute,
  BooksGutenbergIdChaptersIdxRoute: BooksGutenbergIdChaptersIdxRoute,
  ProjectsProjectIdChaptersIdxRoute: ProjectsProjectIdChaptersIdxRoute,
  ProjectsProjectIdChaptersIdxEditRoute: ProjectsProjectIdChaptersIdxEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
